# Generated by Django 2.1.5 on 2019-02-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerece', '0005_auto_20190215_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_picture'),
        ),
    ]
