# Generated by Django 2.1.5 on 2019-02-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerece', '0006_auto_20190215_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=11)),
                ('messsage', models.TextField(blank=True, max_length=300)),
                ('sender_mail', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
