# Generated by Django 2.1.5 on 2019-02-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerece', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='register_user_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
