# Generated by Django 2.1.5 on 2019-03-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerece', '0009_auto_20190317_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convers', to='commerece.Conversation'),
        ),
    ]
