# Generated by Django 2.0.13 on 2019-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerece', '0012_auto_20190329_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_image',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_image',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
