# Generated by Django 2.0.13 on 2019-03-31 17:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_manzoor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_quality', models.CharField(max_length=100)),
                ('product_quentity', models.CharField(max_length=100)),
                ('product_shiping', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_pictures')),
                ('product_image_one', models.ImageField(upload_to='product_pictures_two')),
                ('province', models.CharField(max_length=100)),
                ('city', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('latitude', models.CharField(max_length=100)),
                ('langitudee', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('expire', models.CharField(max_length=100)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
